DOMAIN_DISPLAY_LABELS = {
    "healthcare": "vård och hälsa",
    "tech": "teknik",
    "business": "ekonomi och business",
    "art": "konst, design och musik",
    "humanities": "humaniora och samhälle",
    "law": "juridik",
    "education": "utbildning och lärande",
    "built_environment": "samhällsbyggnad, arkitektur och planering",
    "psychology_social": "psykologi och socialt arbete",
    "environment": "miljö och hållbarhet",
    "media_communication": "media och kommunikation",
}

DOMAIN_KEYWORDS = {
    "healthcare": {
        "vård",
        "healthcare",
        "sjukvård",
        "patient",
        "patientnära",
        "sjuksköterska",
        "nurse",
        "barnmorska",
        "midwife",
        "biomedicin",
        "biomedicine",
        "arbetsterapeut",
        "occupational therapy",
        "fysioterapeut",
        "physiotherapy",
        "medicin",
        "medicine",
        "rehabilitering",
        "rehabilitation",
        "klinisk",
        "clinical",
        "laboratoriemedicin",
        "biomedicinsk analytiker",
        "audionom",
        "läkare",
        "doctor",
        "läkarutbildning",
        "läkarprogrammet",
        "apotekare",
        "pharmacy",
        "farmaci",
        "tandläkare",
        "dentist",
        "odontologi",
        "dietist",
        "dietitian",
        "nutritionist",
        "kost och näring",
        "logoped",
        "speech therapy",
        "speech-language",
        "undersköterska",
        "röntgensjuksköterska",
        "radiografi",
        "radiographer",
        "optiker",
        "optometry",
        "kiropraktor",
        "chiropractic",
        "veterinär",
        "veterinary",
        "medicine",
    },
    "tech": {
        "tech",
        "teknik",
        "technology",
        "ux",
        "user experience",
        "interaktionsdesign",
        "användarupplevelse",
        "anvandarupplevelse",
        "human-computer interaction",
        "hci",
        "människa-teknik",
        "manniska-teknik",
        "interagerar med teknik",
        "ai",
        "artificial intelligence",
        "machine learning",
        "data science",
        "datascience",
        "cybersäkerhet",
        "cybersecurity",
        "software",
        "programmering",
        "programming",
        "computer science",
        "ict",
        "it",
        "engineering",
        "ingenjör",
        "automation",
        "robotics",
        "webbutvecklare",
        "webbutveckling",
        "web development",
        "systemvetare",
        "systemvetenskap",
        "spelutvecklare",
        "spelutveckling",
        "game development",
        "informatik",
        "informatics",
        "information systems",
        "naturvetenskap",
        "natural science",
        "fysik",
        "fysiker",
        "kemi",
        "kemist",
        "matematik",
        "matematiker",
        "brandingenjör",
        "fire safety engineering",
        "sjöingenjör",
        "naval engineering",
        "sjöfart",
        "maritime",
        "maskinteknik",
        "mechanical engineering",
        "elektroteknik",
        "electrical engineering",
        "kemiteknik",
        "chemical engineering",
        "civilingenjör",
        "datateknik",
        "computer engineering",
        "industriell ekonomi",
        "industriell teknik",
        "teknisk fysik",
        "teknisk matematik",
        "energiteknik",
        "bioteknik",
        "miljöteknik",
        "farkostteknik",
        "teknisk design",
    },
    "business": {
        "business",
        "economics",
        "ekonomi",
        "ekonom",
        "finance",
        "finans",
        "management",
        "marknadsföring",
        "marketing",
        "retail",
        "accounting",
        "redovisning",
        "revisor",
        "controller",
        "hr",
        "human resources",
        "personalvetare",
        "finansanalytiker",
        "financial analyst",
        "entrepreneurship",
    },
    "art": {
        "musik",
        "music",
        "musiker",
        "musician",
        "design",
        "grafisk",
        "grafisk designer",
        "graphic designer",
        "konst",
        "art",
        "film",
        "fotografi",
        "photography",
        "fotograf",
        "photographer",
        "skådespelare",
        "actor",
        "teater",
        "theater",
        "dramaturg",
        "dramaturgy",
        "media",
        "fashion",
        "graphic",
        "visual",
        "ljud",
        "musiklärare",
    },
    "humanities": {
        "historia",
        "history",
        "historiker",
        "humaniora",
        "humanities",
        "kultur",
        "culture",
        "samhälle",
        "society",
        "samhällsvetenskap",
        "social science",
        "sociolog",
        "sociology",
        "arkeologi",
        "archaeology",
        "arkeolog",
        "genusvetenskap",
        "gender studies",
        "religionsvetenskap",
        "religious studies",
        "teologi",
        "theology",
        "språk",
        "language",
        "philosophy",
        "filosofi",
        "politics",
        "statsvetenskap",
        "statsvetare",
        "kriminologi",
        "kriminolog",
        "criminology",
    },
    "law": {
        "juridik",
        "law",
        "legal",
        "rättsvetenskap",
        "advokat",
        "lawyer",
        "åklagare",
        "prosecutor",
        "domare",
        "judge",
        "notarie",
        "polis",
        "police",
        "polisutbildning",
        "compliance",
        "domstol",
        "court",
        "affärsjuridik",
        "human rights law",
        "migrationsrätt",
    },
    "education": {
        "lärare",
        "teacher",
        "undervisning",
        "pedagogik",
        "education",
        "specialpedagogik",
        "specialpedagog",
        "special education",
        "förskollärare",
        "förskolelärare",
        "fritidspedagog",
        "rektor",
        "school principal",
        "grundskollärare",
        "gymnasielärare",
        "primary education",
        "secondary education",
        "skola",
    },
    "built_environment": {
        "arkitektur",
        "arkitekt",
        "arkitektutbildning",
        "architecture",
        "architect",
        "stadsplanering",
        "urban planning",
        "planering",
        "samhällsbyggnad",
        "samhällsplanerare",
        "stadsplanerare",
        "urbanism",
        "landskap",
        "landscape",
        "bygg",
        "byggnadsteknik",
        "construction",
        "real estate development",
        "spatial planning",
        "fastighetsutveckling",
        "fastighetsekonomi",
        "fastighetsmäklare",
        "real estate agent",
        "inredning",
        "inredningsarkitekt",
        "interior design",
    },
    "psychology_social": {
        "psykologi",
        "psychology",
        "psykolog",
        "socialt arbete",
        "social work",
        "socionom",
        "beteendevetare",
        "kurator",
        "counselling",
        "mental health",
        "beteendevetenskap",
        "behavioral science",
        "terapi",
        "therapy",
        "psykoterapeut",
        "psychotherapy",
        "wellbeing",
    },
    "environment": {
        "hållbarhet",
        "sustainability",
        "hållbarhetsstrateg",
        "miljö",
        "miljökonsult",
        "miljövetare",
        "environment",
        "climate",
        "klimat",
        "green transition",
        "circular economy",
        "ecology",
        "ekologi",
        "biologi",
        "biology",
        "biolog",
        "geologi",
        "geology",
        "geolog",
        "meteorologi",
        "meteorology",
        "meteorolog",
        "renewable",
        "energiomställning",
    },
    "media_communication": {
        "media",
        "kommunikation",
        "kommunikatör",
        "communication",
        "journalistik",
        "journalism",
        "journalist",
        "medievetenskap",
        "media studies",
        "pr",
        "public relations",
        "content",
        "branding",
        "copywriting",
        "digital media",
        "strategic communication",
    },
}

TRACK_KEYWORDS = {
    "healthcare": {
        "patient_care": {
            "patientnära",
            "patient",
            "sjuksköterska",
            "nurse",
            "barnmorska",
            "midwife",
            "kliniskt arbete",
            "clinical practice",
            "care",
        },
        "rehabilitation": {
            "rehabilitering",
            "rehabilitation",
            "arbetsterapeut",
            "occupational therapy",
            "fysioterapeut",
            "physiotherapy",
        },
        "diagnostics_lab": {
            "biomedicin",
            "biomedicine",
            "biomedicinsk analytiker",
            "clinical physiology",
            "diagnostik",
            "lab",
            "laboratorium",
        },
        "public_health": {
            "folkhälsa",
            "public health",
            "hälsopolitik",
            "epidemiology",
            "global health",
        },
        "health_tech": {
            "health tech",
            "medtech",
            "medical technology",
            "digital health",
            "health informatics",
        },
    },
    "tech": {
        "ai_data": {
            "ai",
            "artificial intelligence",
            "machine learning",
            "data science",
            "analytics",
            "computer vision",
        },
        "cybersecurity": {
            "cybersäkerhet",
            "cybersecurity",
            "information security",
            "security",
        },
        "software": {
            "software",
            "programmering",
            "programming",
            "computer science",
            "developer",
            "utvecklare",
        },
        "ux_hci": {
            "ux",
            "user experience",
            "interaktionsdesign",
            "användarupplevelse",
            "anvandarupplevelse",
            "human-computer interaction",
            "hci",
            "interaction design",
            "usability",
            "digital product design",
            "user research",
        },
        "embedded_automation": {
            "embedded",
            "automation",
            "robotics",
            "control systems",
            "mechatronics",
        },
        "engineering": {
            "maskinteknik",
            "mechanical engineering",
            "elektroteknik",
            "electrical engineering",
            "kemiteknik",
            "chemical engineering",
            "civilingenjör",
            "datateknik",
            "computer engineering",
            "industriell teknik",
            "teknisk fysik",
            "teknisk matematik",
            "energiteknik",
            "miljöteknik",
            "farkostteknik",
            "teknisk design",
        },
    },
    "business": {
        "finance": {
            "finance",
            "finans",
            "investment",
            "accounting",
            "redovisning",
            "economics",
            "ekonomi",
            "econometrics",
        },
        "management": {
            "management",
            "leadership",
            "organisation",
            "business administration",
        },
        "business_analytics": {
            "business analytics",
            "analytics",
            "analys",
            "data-driven",
            "data",
            "information systems",
            "business intelligence",
            "digital business",
        },
        "product_management": {
            "product management",
            "produktledning",
            "digital product",
            "innovation",
            "innovation technology",
            "technology management",
            "information systems",
            "business development",
            "verksamhetsutveckling",
            "digital transformation",
        },
        "marketing_sales": {
            "marketing",
            "marknadsföring",
            "sales",
            "retail",
            "branding",
        },
    },
    "art": {
        "music": {
            "musik",
            "music",
            "songwriting",
            "composition",
            "performance",
        },
        "design": {
            "design",
            "graphic",
            "visual",
            "fashion",
            "industrial design",
        },
        "film_media": {
            "film",
            "media",
            "animation",
            "photo",
            "photography",
        },
    },
    "humanities": {
        "history_culture": {
            "historia",
            "history",
            "kultur",
            "culture",
            "arkeologi",
            "archaeology",
            "heritage",
            "kulturarv",
        },
        "languages_communication": {
            "språk",
            "language",
            "communication",
            "kommunikation",
            "literature",
            "litteratur",
        },
        "society_policy": {
            "society",
            "samhälle",
            "politics",
            "statsvetenskap",
            "policy",
            "public affairs",
        },
    },
    "law": {
        "legal_practice": {
            "juridik",
            "law",
            "legal",
            "advokat",
            "lawyer",
            "domstol",
            "court",
        },
        "business_law": {
            "affärsjuridik",
            "business law",
            "compliance",
            "corporate law",
            "contract",
            "avtal",
        },
        "public_international_law": {
            "public law",
            "international law",
            "human rights",
            "mänskliga rättigheter",
            "migration",
            "migrationsrätt",
            "policy",
        },
    },
    "education": {
        "teaching": {
            "lärare",
            "teacher",
            "undervisning",
            "teaching",
            "skola",
            "classroom",
        },
        "special_education": {
            "specialpedagogik",
            "special education",
            "speciallärare",
            "inkludering",
            "support in school",
        },
        "educational_leadership": {
            "pedagogik",
            "education",
            "learning",
            "utbildningsledning",
            "educational leadership",
        },
    },
    "built_environment": {
        "urban_planning": {
            "stadsplanering",
            "urban planning",
            "samhällsbyggnad",
            "spatial planning",
            "city development",
        },
        "architecture_design": {
            "arkitektur",
            "architecture",
            "landskap",
            "landscape",
            "byggnadsdesign",
        },
        "sustainable_construction": {
            "construction",
            "bygg",
            "hållbart byggande",
            "sustainable building",
            "real estate development",
        },
    },
    "psychology_social": {
        "psychology": {
            "psykologi",
            "psychology",
            "mental health",
            "therapy",
            "behavioral science",
        },
        "social_work": {
            "socialt arbete",
            "social work",
            "kurator",
            "welfare",
            "community support",
        },
        "counselling_people": {
            "counselling",
            "rådgivning",
            "wellbeing",
            "coaching",
            "support",
        },
    },
    "environment": {
        "sustainability_management": {
            "hållbarhet",
            "sustainability",
            "green transition",
            "circular economy",
        },
        "environmental_science": {
            "miljö",
            "environment",
            "ecology",
            "ekologi",
            "climate",
            "klimat",
        },
        "energy_transition": {
            "renewable",
            "energiomställning",
            "energy systems",
            "sustainable energy",
        },
    },
    "media_communication": {
        "journalism_media": {
            "journalistik",
            "journalism",
            "media",
            "digital media",
            "editorial",
        },
        "strategic_communication": {
            "kommunikation",
            "communication",
            "pr",
            "public relations",
            "strategic communication",
        },
        "content_branding": {
            "content",
            "branding",
            "copywriting",
            "marketing communication",
            "storytelling",
        },
    },
}

DOMAIN_SPECIFIC_ROLE_TERMS = {
    "healthcare": {
        "sjuksköterska",
        "nurse",
        "barnmorska",
        "midwife",
        "arbetsterapeut",
        "occupational therapy",
        "fysioterapeut",
        "physiotherapy",
        "biomedicinsk analytiker",
        "biomedicine",
        "biomedicin",
        "audionom",
        "läkare",
        "doctor",
        "apotekare",
        "farmaci",
        "tandläkare",
        "odontologi",
        "dietist",
        "logoped",
        "undersköterska",
        "röntgensjuksköterska",
        "optiker",
        "kiropraktor",
        "veterinär",
        "medicine",
    },
    "tech": {
        "it",
        "information technology",
        "informationsteknik",
        "data science",
        "cybersecurity",
        "software",
        "computer science",
        "machine learning",
        "ai",
        "automation",
        "ingenjör",
        "maskinteknik",
        "elektroteknik",
        "datateknik",
        "civilingenjör",
        "kemiteknik",
        "webbutvecklare",
        "systemvetare",
        "spelutvecklare",
        "fysiker",
        "kemist",
        "matematiker",
        "brandingenjör",
        "informatik",
        "naturvetenskap",
        "sjöingenjör",
        "systemvetenskap",
        "mjukvara",
        "programmering",
        "programmering",
        "webb",
        "digital",
    },
    "business": {
        "finance",
        "finans",
        "economics",
        "ekonomi",
        "management",
        "marketing",
        "marknadsföring",
        "retail",
        "redovisning",
        "accounting",
        "revisor",
        "controller",
        "hr",
        "human resources",
        "personalvetare",
        "finansanalytiker",
        "ekonom",
        "entrepreneurship",
    },
    "art": {
        "music",
        "musik",
        "musiker",
        "design",
        "grafisk designer",
        "fotograf",
        "skådespelare",
        "dramaturg",
        "film",
        "media",
    },
    "humanities": {
        "history",
        "historia",
        "historiker",
        "culture",
        "kultur",
        "humanities",
        "humaniora",
        "language",
        "språk",
        "arkeolog",
        "sociolog",
        "statsvetare",
        "kriminolog",
        "samhällsvetenskap",
        "genusvetenskap",
        "religionsvetenskap",
        "society",
        "samhälle",
    },
    "law": {
        "law",
        "legal",
        "juridik",
        "advokat",
        "åklagare",
        "domare",
        "notarie",
        "polis",
        "compliance",
        "human rights",
    },
    "education": {
        "teacher",
        "lärare",
        "förskollärare",
        "förskolelärare",
        "specialpedagog",
        "fritidspedagog",
        "rektor",
        "grundskollärare",
        "gymnasielärare",
        "teaching",
        "pedagogik",
        "education",
    },
    "built_environment": {
        "architecture",
        "arkitektur",
        "arkitekt",
        "arkitektutbildning",
        "urban planning",
        "stadsplanering",
        "samhällsbyggnad",
        "samhällsplanerare",
        "stadsplanerare",
        "construction",
        "byggnadsteknik",
        "landscape",
        "fastighetsutveckling",
        "fastighetsekonomi",
        "fastighetsmäklare",
        "inredningsarkitekt",
    },
    "psychology_social": {
        "psychology",
        "psykologi",
        "psykolog",
        "social work",
        "socialt arbete",
        "socionom",
        "sociolog",
        "beteendevetare",
        "mental health",
        "behavioral science",
        "psykoterapeut",
        "psychotherapy",
    },
    "environment": {
        "sustainability",
        "hållbarhet",
        "hållbarhetsstrateg",
        "environment",
        "miljö",
        "miljökonsult",
        "miljövetare",
        "biolog",
        "geolog",
        "meteorolog",
        "climate",
        "energy transition",
    },
    "media_communication": {
        "media",
        "communication",
        "kommunikation",
        "kommunikatör",
        "journalism",
        "journalist",
        "medievetenskap",
        "branding",
        "pr",
    },
}

DOMAIN_FOLLOW_UP_QUESTIONS = {
    "healthcare": [
        "Vill du arbeta direkt med patienter, med rehabilitering eller med laboratoriemedicin?",
        "Söker du en grundutbildning eller en vidareutbildning/master?",
        "Har du en särskild stad i åtanke eller vill du se alternativ i hela Sverige?",
    ],
    "tech": [
        "Är du mest intresserad av AI och data, cybersäkerhet, mjukvaruutveckling eller automation?",
        "Letar du efter kandidat eller master?",
        "Vill du prioritera en viss stad eller är ämnet viktigare än platsen?",
    ],
    "business": [
        "Är du mest intresserad av ekonomi, finans, management eller marknadsföring?",
        "Söker du kandidat eller master?",
        "Vill du läsa på engelska eller svenska?",
    ],
    "art": [
        "Är du främst ute efter musik, design eller film och media?",
        "Vill du ha en mer praktisk eller mer teoretisk utbildning?",
        "Har du en särskild stad eller skola i åtanke?",
    ],
    "humanities": [
        "Är du mest intresserad av historia och kultur, språk och kommunikation eller samhällsfrågor?",
        "Vill du kombinera humaniora med ett annat område, till exempel teknik eller media?",
        "Har du en särskild stad eller nivå i åtanke?",
    ],
    "law": [
        "Är du mest intresserad av klassisk juridik, affärsjuridik eller offentlig/internationell rätt?",
        "Vill du arbeta mer med rådgivning, förhandling eller samhälls- och policyfrågor?",
        "Söker du en bred juristutbildning eller ett mer nischat rättsområde?",
    ],
    "education": [
        "Vill du arbeta som lärare i klassrum, med specialpedagogik eller mer med lärande och utbildningsutveckling?",
        "Vilken åldersgrupp lockar mest: förskola, grundskola, gymnasium eller vuxenutbildning?",
        "Är du ute efter en yrkesexamen eller ett bredare pedagogikspår?",
    ],
    "built_environment": [
        "Lockar stadsplanering, arkitektur eller hållbart byggande mest?",
        "Vill du arbeta mer med design, samhällsplanering eller tekniskt genomförande?",
        "Är hållbarhet, estetik eller praktisk samhällsutveckling viktigast för dig?",
    ],
    "psychology_social": [
        "Är du mest intresserad av psykologi, socialt arbete eller rådgivande stöd till människor?",
        "Vill du arbeta mer med individers välmående, beteenden eller samhälleliga stödinsatser?",
        "Söker du ett kliniskt, socialt eller mer organisationsnära spår?",
    ],
    "environment": [
        "Lockar hållbarhetsarbete, miljövetenskap eller energiomställning mest?",
        "Vill du arbeta mer strategiskt med hållbarhet eller mer naturvetenskapligt med miljöfrågor?",
        "Är klimat, ekologi eller grön omställning viktigast för dig?",
    ],
    "media_communication": [
        "Är du mest intresserad av journalistik, strategisk kommunikation eller innehåll och branding?",
        "Vill du arbeta mer med berättande, analys eller varumärkesbyggande?",
        "Lockar mediahus, byråvärld eller kommunikation i organisationer mest?",
    ],
    "other": [
        "Vilket område är du mest intresserad av: teknik, vård, ekonomi, konst eller något annat?",
        "Söker du kandidat eller master?",
        "Har du en stad eller ett språk du vill prioritera?",
    ],
}

BRIDGE_PATHS = {
    ("healthcare", "tech"): [
        {
            "id": "health_tech",
            "label": "health tech och medicinteknik",
            "question": "Är du mer intresserad av vårdteknik och digital hälsa än av direkt patientarbete?",
            "domains": ["healthcare", "tech"],
            "tracks": ["health_tech"],
            "next_questions": [
                "Lockar medicinteknik, digital hälsa eller teknik nära klinisk vardag mest?",
                "Vill du arbeta närmare produkter och system eller närmare vårdverksamhetens behov?",
            ],
        },
        {
            "id": "clinical_informatics",
            "label": "hälsoinformatik och digital vårdutveckling",
            "question": "Lockar digitalisering av vården, data eller systemstöd inom sjukvården mest?",
            "domains": ["healthcare", "tech"],
            "tracks": ["health_tech"],
            "next_questions": [
                "Vill du arbeta mer med vårddata och analys eller mer med system och digitala arbetsflöden?",
                "Lockar sjukhus och vårdverksamheter mer än teknikbolag och produktutveckling?",
            ],
        },
    ],
    ("business", "tech"): [
        {
            "id": "business_analytics",
            "label": "business analytics",
            "question": "Är du ute efter analys och datadrivna beslut snarare än ren programmering?",
            "domains": ["business", "tech"],
            "tracks": ["business_analytics"],
            "next_questions": [
                "Vill du arbeta mer med analys, data och beslutsstöd än med ren systemutveckling?",
                "Lockar affärsanalys, business intelligence eller digital verksamhetsutveckling mest?",
            ],
        },
        {
            "id": "product_management",
            "label": "produktledning i teknikbolag",
            "question": "Vill du hellre arbeta i skärningen mellan affär och teknik än som ren utvecklare?",
            "domains": ["business", "tech"],
            "tracks": ["product_management"],
            "next_questions": [
                "Vill du arbeta närmare produktstrategi och prioriteringar än ren kodning?",
                "Lockar teknikbolag, digitala produkter eller affärsnära utvecklingsroller mest?",
            ],
        },
    ],
    ("humanities", "tech"): [
        {
            "id": "digital_humanities",
            "label": "digital humaniora",
            "question": "Vill du använda teknik för att arbeta med historia, kulturarv eller digitala samlingar?",
            "domains": ["humanities", "tech"],
            "tracks": ["history_culture"],
            "next_questions": [
                "Vill du helst arbeta med kulturarv, historia eller digitala samlingar?",
                "Söker du en mer teknisk utbildning eller en mer humanistisk med digital inriktning?",
            ],
        },
        {
            "id": "information_science",
            "label": "informationsvetenskap, bibliotek och arkiv",
            "question": "Är informationshantering, arkiv eller digital kunskapsorganisation mest intressant för dig?",
            "domains": ["humanities", "tech"],
            "tracks": ["languages_communication"],
            "next_questions": [
                "Vill du arbeta med informationshantering, bibliotek och arkiv eller mer med digital kunskapsorganisation?",
                "Är en samhällsnära eller mer teknisk profil viktigast för dig?",
            ],
        },
        {
            "id": "ux_interaction_design",
            "label": "UX och interaktionsdesign",
            "question": "Lockar teknik som utgår från människor, beteenden och användarupplevelse mer än ren ingenjörsteknik?",
            "domains": ["tech", "art"],
            "tracks": [],
            "next_questions": [
                "Vill du arbeta med design av digitala produkter, användarresearch eller interaktionsdesign?",
                "Föredrar du ett mer tekniskt eller mer designnära spår?",
            ],
        },
    ],
    ("art", "tech"): [
        {
            "id": "creative_technology",
            "label": "kreativ teknik och medieteknik",
            "question": "Vill du kombinera skapande med digital produktion, interaktiv media eller ljudteknik?",
            "domains": ["art", "tech"],
            "tracks": [],
            "next_questions": [
                "Är du mest intresserad av interaktiv media, medieteknik eller digital produktion?",
                "Vill du ha ett mer tekniskt eller mer skapande program?",
            ],
        },
        {
            "id": "music_technology",
            "label": "musik- och ljudteknik",
            "question": "Är du ute efter att jobba med musikskapande via teknik snarare än ren musikutbildning?",
            "domains": ["art", "tech"],
            "tracks": ["music"],
            "next_questions": [
                "Vill du främst arbeta med ljudproduktion, musikskapande eller tekniken bakom studio och live?",
                "Är det viktigare att utbildningen lutar åt musik eller åt teknik?",
            ],
        },
    ],
    ("law", "tech"): [
        {
            "id": "legal_tech",
            "label": "legal tech och digital regelefterlevnad",
            "question": "Lockar juridik i kombination med digitalisering, compliance eller AI-reglering mer än traditionell juristbana?",
            "domains": ["law", "tech"],
            "tracks": ["business_law"],
            "next_questions": [
                "Är du mer intresserad av compliance, dataskydd och AI-reglering eller av bred affärsjuridik?",
                "Vill du arbeta närmare teknikbolag och digitala produkter än domstol och traditionell juridik?",
            ],
        }
    ],
    ("education", "tech"): [
        {
            "id": "edtech_learning_design",
            "label": "edtech och lärandedesign",
            "question": "Vill du kombinera pedagogik med digitala verktyg, lärplattformar eller utbildningsteknik?",
            "domains": ["education", "tech"],
            "tracks": ["educational_leadership"],
            "next_questions": [
                "Lockar undervisningsdesign, digitala lärresurser eller utbildningsutveckling mest?",
                "Vill du arbeta närmare skolan eller närmare teknik- och produktutveckling?",
            ],
        }
    ],
    ("built_environment", "tech"): [
        {
            "id": "smart_cities",
            "label": "smart cities och digital samhällsplanering",
            "question": "Vill du kombinera samhällsplanering med data, digital infrastruktur eller smarta stadsfunktioner?",
            "domains": ["built_environment", "tech"],
            "tracks": ["urban_planning"],
            "next_questions": [
                "Är du mest intresserad av stadsdata, hållbar mobilitet eller digital planering?",
                "Vill du arbeta mer strategiskt med planering eller mer tekniskt med system och analys?",
            ],
        }
    ],
    ("environment", "tech"): [
        {
            "id": "climate_tech",
            "label": "climate tech och hållbar teknik",
            "question": "Vill du kombinera hållbarhet med teknik, data eller energiomställning snarare än ren miljövetenskap?",
            "domains": ["environment", "tech"],
            "tracks": ["energy_transition", "sustainability_management"],
            "next_questions": [
                "Lockar energiomställning, hållbar produktutveckling eller klimatdata mest?",
                "Vill du arbeta mer tekniskt med system och teknik eller mer strategiskt med hållbarhetsfrågor?",
            ],
        }
    ],
    ("media_communication", "tech"): [
        {
            "id": "digital_media_communication",
            "label": "digital media, kommunikation och plattformar",
            "question": "Vill du kombinera kommunikation och media med digitala plattformar, analys eller produktion?",
            "domains": ["media_communication", "tech"],
            "tracks": ["journalism_media", "strategic_communication"],
            "next_questions": [
                "Är du mer intresserad av innehåll och berättande eller av digital analys och plattformar?",
                "Vill du arbeta närmare media, marknad eller produktteam?",
            ],
        }
    ],
    ("psychology_social", "tech"): [
        {
            "id": "behavioural_ux",
            "label": "UX, interaktionsdesign och människa-teknik",
            "question": "Vill du kombinera psykologi och beteendevetenskap med digitala produkter och användarupplevelse?",
            "domains": ["psychology_social", "tech"],
            "tracks": ["psychology", "ux_hci"],
            "next_questions": [
                "Lockar användarbeteende, research eller design av digitala upplevelser mest?",
                "Vill du arbeta mer med människor och beteenden eller mer med digital produktutveckling?",
            ],
        }
    ],
    ("psychology_social", "business"): [
        {
            "id": "consumer_behaviour_people_business",
            "label": "konsumentbeteende, people analytics och organisationsutveckling",
            "question": "Är du intresserad av hur människor tänker och beter sig i organisationer, marknad eller arbetsliv?",
            "domains": ["psychology_social", "business"],
            "tracks": ["psychology", "management"],
            "next_questions": [
                "Lockar organisationsutveckling, HR, marknad eller analys av beteenden mest?",
                "Vill du arbeta mer med individer, team eller affärsbeslut?",
            ],
        }
    ],
    ("environment", "business"): [
        {
            "id": "sustainability_strategy_esg",
            "label": "hållbarhetsledning, ESG och grön affärsutveckling",
            "question": "Vill du kombinera hållbarhet med strategi, affär och organisation snarare än ren teknik eller naturvetenskap?",
            "domains": ["environment", "business"],
            "tracks": ["sustainability_management", "management"],
            "next_questions": [
                "Lockar hållbarhetsstrategi, ESG-rapportering eller grön affärsutveckling mest?",
                "Vill du arbeta i företag, offentlig sektor eller konsultnära roller?",
            ],
        }
    ],
    ("law", "business"): [
        {
            "id": "business_law_compliance",
            "label": "affärsjuridik, compliance och regelefterlevnad",
            "question": "Är du mer intresserad av juridik kopplad till företag, affärer och regelefterlevnad än av domstol och klassisk juristbana?",
            "domains": ["law", "business"],
            "tracks": ["business_law", "management"],
            "next_questions": [
                "Lockar affärsjuridik, compliance eller risk och governance mest?",
                "Vill du arbeta närmare företag och affärer än traditionella rättsliga miljöer?",
            ],
        }
    ],
    ("psychology_social", "education"): [
        {
            "id": "student_support_learning",
            "label": "studenthälsa, pedagogiskt stöd och lärandemiljöer",
            "question": "Vill du kombinera psykologi och stöd till människor med lärande, skola eller utbildningsmiljöer?",
            "domains": ["psychology_social", "education"],
            "tracks": ["counselling_people", "special_education"],
            "next_questions": [
                "Är du mer intresserad av elevstöd, specialpedagogik eller lärandemiljöer?",
                "Vill du arbeta närmare individers välmående eller närmare skolans pedagogiska utveckling?",
            ],
        }
    ],
    ("media_communication", "business"): [
        {
            "id": "brand_strategy_communication",
            "label": "brand strategy, innehåll och kommunikation",
            "question": "Vill du kombinera kommunikation och innehåll med affär, varumärke och marknad snarare än ren media eller journalistik?",
            "domains": ["media_communication", "business"],
            "tracks": ["content_branding", "marketing_sales"],
            "next_questions": [
                "Lockar varumärkesstrategi, innehåll eller marknadskommunikation mest?",
                "Vill du arbeta mer kreativt med innehåll eller mer strategiskt med affär och positionering?",
            ],
        }
    ],
}

SOCIETY_TECH_BRIDGE_PATHS = [
    {
        "id": "computational_social_science",
        "label": "computational social science",
        "question": "Vill du använda data och programmering för att förstå samhälle, beteenden eller policyfrågor?",
        "domains": ["humanities", "tech"],
        "tracks": ["society_policy"],
        "next_questions": [
            "Är du mest intresserad av dataanalys om samhälle och beteenden eller av AI i policy och offentlig sektor?",
            "Vill du ha ett mer tekniskt eller mer samhällsvetenskapligt program?",
        ],
    },
    {
        "id": "ai_policy_digital_society",
        "label": "AI, policy och digitalt samhälle",
        "question": "Lockar frågor om hur AI påverkar samhälle, demokrati och offentlig sektor mer än ren utveckling?",
        "domains": ["humanities", "tech"],
        "tracks": ["society_policy"],
        "next_questions": [
            "Vill du arbeta med policy, offentlig sektor eller analys av AI:s samhällseffekter?",
            "Föredrar du ett program med tydlig samhällsvetenskaplig profil eller mer teknikinslag?",
        ],
    },
    {
        "id": "civic_technology",
        "label": "civic tech och digital samhällsutveckling",
        "question": "Vill du använda teknik för att förbättra samhällstjänster, medborgardialog eller offentlig verksamhet?",
        "domains": ["humanities", "tech"],
        "tracks": ["society_policy"],
        "next_questions": [
            "Är offentlig sektor, samhällsutveckling eller digital serviceutveckling mest intressant för dig?",
            "Vill du jobba nära användare och organisationer eller mer med analys och data?",
        ],
    },
]

MOTIVATION_GUIDANCE = {
    "people_oriented": {
        "answer": "Det låter som att du vill arbeta nära människor, men ännu inte vet vilket typ av sammanhang som passar dig bäst.",
        "answer_en": "It sounds like you want to work closely with people, but aren't sure yet which type of context suits you best.",
        "options": [
            {
                "id": "patient_care_path",
                "label": "patientnära arbete inom vård",
                "label_en": "patient-facing work in healthcare",
                "domains": ["healthcare"],
                "tracks": ["patient_care"],
                "next_questions": [
                    "Vill du främst arbeta med omvårdnad, diagnostik eller rehabilitering?",
                    "Söker du kandidatnivå eller vidareutbildning inom vård?",
                ],
            },
            {
                "id": "rehabilitation_path",
                "label": "rehabilitering och stöd till människor",
                "label_en": "rehabilitation and support for people",
                "domains": ["healthcare"],
                "tracks": ["rehabilitation"],
                "next_questions": [
                    "Lockar arbetsterapi eller fysioterapi mer än klassisk omvårdnad?",
                    "Vill du arbeta praktiskt med människors återhämtning och funktion i vardagen?",
                ],
            },
            {
                "id": "society_people_path",
                "label": "människonära arbete inom samhälle, stöd eller rådgivning",
                "label_en": "people-centred work in society, support or counselling",
                "domains": ["humanities"],
                "tracks": ["society_policy"],
                "next_questions": [
                    "Är du mer intresserad av rådgivning, samhällsfrågor eller stödjande arbete än av vård?",
                    "Vill du arbeta i offentlig sektor, organisationer eller utbildningsnära roller?",
                ],
            },
            {
                "id": "teaching_people_path",
                "label": "läraryrken och pedagogiskt arbete",
                "label_en": "teaching and educational roles",
                "domains": ["education"],
                "tracks": ["teaching"],
                "next_questions": [
                    "Vill du arbeta i klassrum, med specialpedagogik eller med lärandeutveckling?",
                    "Vilken åldersgrupp vill du helst arbeta med?",
                ],
            },
            {
                "id": "psychology_people_path",
                "label": "psykologi, socialt arbete och stödjande roller",
                "label_en": "psychology, social work and supporting roles",
                "domains": ["psychology_social"],
                "tracks": ["psychology", "social_work"],
                "next_questions": [
                    "Är du mer intresserad av psykologi och beteende eller av socialt arbete och stödinsatser?",
                    "Vill du arbeta mer med individers välmående eller med samhälleliga stödstrukturer?",
                ],
            },
        ],
    },
    "creative_career": {
        "answer": "Det låter som att du vill kombinera kreativitet med rimliga jobbchanser, vilket är en bra vägledningsfråga men fortfarande för brett för att hoppa direkt till program.",
        "answer_en": "It sounds like you want to combine creativity with solid career prospects — a good guidance question, but still too broad to jump straight to programmes.",
        "options": [
            {
                "id": "ux_design_path",
                "label": "UX, interaktionsdesign och digital produktdesign",
                "label_en": "UX, interaction design and digital product design",
                "domains": ["tech", "art"],
                "tracks": [],
                "next_questions": [
                    "Vill du jobba med användarupplevelse, digital design eller produktutveckling?",
                    "Är ett mer tekniskt eller mer visuellt/designnära program bäst för dig?",
                ],
            },
            {
                "id": "design_media_path",
                "label": "design, media och skapande",
                "label_en": "design, media and creative work",
                "domains": ["art"],
                "tracks": ["design"],
                "next_questions": [
                    "Är du mest intresserad av grafisk design, visuell kommunikation eller media?",
                    "Är du beredd att ta mer osäkra jobbchanser för högre kreativ frihet?",
                ],
            },
            {
                "id": "creative_business_path",
                "label": "marknadsföring, kommunikation och kreativa affärsroller",
                "label_en": "marketing, communications and creative business roles",
                "domains": ["business", "humanities"],
                "tracks": ["marketing_sales", "languages_communication"],
                "next_questions": [
                    "Lockar marknadsföring, kommunikation eller branding mer än ren design?",
                    "Vill du kombinera kreativitet med affär och tydligare arbetsmarknad?",
                ],
            },
            {
                "id": "media_communication_path",
                "label": "media, kommunikation och digitalt innehåll",
                "label_en": "media, communications and digital content",
                "domains": ["media_communication"],
                "tracks": ["journalism_media", "content_branding"],
                "next_questions": [
                    "Är du mer intresserad av journalistik, kommunikation eller innehållsproduktion?",
                    "Vill du jobba närmare media, byrå eller organisationers kommunikation?",
                ],
            },
        ],
    },
    "salary_focus": {
        "answer": "Hög lön är ett rimligt mål, men det räcker inte för att ge bra programförslag utan att förstå vilken typ av arbete du kan tänka dig.",
        "answer_en": "A high salary is a reasonable goal, but it's not enough to give good programme suggestions without understanding what kind of work you can picture yourself doing.",
        "options": [
            {
                "id": "salary_tech_path",
                "label": "teknik, data och digital produktutveckling",
                "label_en": "technology, data and digital product development",
                "domains": ["tech"],
                "tracks": ["ai_data", "software"],
                "next_questions": [
                    "Är du mer intresserad av AI och data eller av mjukvaruutveckling?",
                    "Vill du ha en tekniskt tung utbildning eller något mer tillämpat och affärsnära?",
                ],
            },
            {
                "id": "salary_business_path",
                "label": "ekonomi, finans och affär",
                "label_en": "economics, finance and business",
                "domains": ["business"],
                "tracks": ["finance", "management"],
                "next_questions": [
                    "Lockar finans, ekonomi eller management mest?",
                    "Vill du arbeta i en mer analytisk eller mer kommersiell roll?",
                ],
            },
            {
                "id": "salary_health_path",
                "label": "specialiserade vård- och hälsospår med stabil efterfrågan",
                "label_en": "specialised healthcare tracks with stable demand",
                "domains": ["healthcare"],
                "tracks": ["patient_care", "diagnostics_lab"],
                "next_questions": [
                    "Är du öppen för vårdspår där trygg arbetsmarknad väger tyngre än maximal lön?",
                    "Vill du arbeta patientnära eller mer med diagnostik och analys?",
                ],
            },
        ],
    },
    "future_focus": {
        "answer": "Bra framtidsmöjligheter är ett rimligt mål, men jag behöver förstå vilken typ av arbete och vardag du kan tänka dig innan jag pekar ut utbildningar.",
        "answer_en": "Good future prospects are a reasonable goal, but I need to understand what kind of work and daily life you can picture before pointing to programmes.",
        "options": [
            {
                "id": "future_tech_path",
                "label": "teknik, data och digital utveckling",
                "label_en": "technology, data and digital development",
                "domains": ["tech"],
                "tracks": ["ai_data", "software"],
                "next_questions": [
                    "Lockar AI och data mer än mjukvaruutveckling och system?",
                    "Vill du ha ett mer tekniskt eller mer tillämpat spår?",
                ],
            },
            {
                "id": "future_business_path",
                "label": "ekonomi, analys och affär",
                "label_en": "economics, analysis and business",
                "domains": ["business"],
                "tracks": ["finance", "management"],
                "next_questions": [
                    "Är du mer intresserad av ekonomi och analys eller av affär och management?",
                    "Vill du ha en bred utbildning eller ett mer specialiserat affärsspår?",
                ],
            },
            {
                "id": "future_health_path",
                "label": "vård, hälsa och andra yrken med stabil efterfrågan",
                "label_en": "healthcare and other professions with stable demand",
                "domains": ["healthcare"],
                "tracks": ["patient_care", "diagnostics_lab"],
                "next_questions": [
                    "Är du öppen för vård och hälsospår där efterfrågan är stabil över tid?",
                    "Vill du arbeta patientnära eller mer med analys, diagnostik och labb?",
                ],
            },
        ],
    },
}
